import Navbar from "./components/Navbar";

import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { Akshar } from "next/font/google";
const akshar = Akshar({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={akshar.className}>
        <Navbar />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
